/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * E-commerce store API
 * OpenAPI spec version: 0.1.0
 */

export interface ProductSalesStats {
  productId: number;
  productName: string;
  /** @nullable */
  productImageUrl?: string | null;
  totalSold: number;
  revenue: number;
}
