/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * E-commerce store API
 * OpenAPI spec version: 0.1.0
 */

export interface OrderItem {
  id: number;
  orderId: number;
  productId: number;
  productName?: string;
  /** @nullable */
  productImageUrl?: string | null;
  quantity: number;
  unitPrice: number;
  total: number;
}
