/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * E-commerce store API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary List all categories
 */
export const ListCategoriesResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().nullish(),
  "imageUrl": zod.string().nullish(),
  "productCount": zod.number().optional(),
  "createdAt": zod.string().optional()
})
export const ListCategoriesResponse = zod.array(ListCategoriesResponseItem)


/**
 * @summary Create a category
 */
export const CreateCategoryBody = zod.object({
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().optional(),
  "imageUrl": zod.string().optional()
})


/**
 * @summary Get a category by ID
 */
export const GetCategoryParams = zod.object({
  "id": zod.coerce.number()
})

export const GetCategoryResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().nullish(),
  "imageUrl": zod.string().nullish(),
  "productCount": zod.number().optional(),
  "createdAt": zod.string().optional()
})


/**
 * @summary Update a category
 */
export const UpdateCategoryParams = zod.object({
  "id": zod.coerce.number()
})

export const UpdateCategoryBody = zod.object({
  "name": zod.string().optional(),
  "slug": zod.string().optional(),
  "description": zod.string().optional(),
  "imageUrl": zod.string().optional()
})

export const UpdateCategoryResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().nullish(),
  "imageUrl": zod.string().nullish(),
  "productCount": zod.number().optional(),
  "createdAt": zod.string().optional()
})


/**
 * @summary Delete a category
 */
export const DeleteCategoryParams = zod.object({
  "id": zod.coerce.number()
})


/**
 * @summary List products with optional filters
 */
export const ListProductsQueryParams = zod.object({
  "categoryId": zod.coerce.number().optional(),
  "search": zod.coerce.string().optional(),
  "minPrice": zod.coerce.number().optional(),
  "maxPrice": zod.coerce.number().optional(),
  "inStock": zod.coerce.boolean().optional(),
  "page": zod.coerce.number().optional(),
  "limit": zod.coerce.number().optional()
})

export const ListProductsResponse = zod.object({
  "products": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().nullish(),
  "price": zod.number(),
  "comparePrice": zod.number().nullish(),
  "imageUrl": zod.string().nullish(),
  "images": zod.array(zod.string()).optional(),
  "stock": zod.number(),
  "sku": zod.string().nullish(),
  "categoryId": zod.number(),
  "categoryName": zod.string().nullish(),
  "isFeatured": zod.boolean().optional(),
  "rating": zod.number().nullish(),
  "reviewCount": zod.number().optional(),
  "createdAt": zod.string().optional()
})),
  "total": zod.number(),
  "page": zod.number(),
  "limit": zod.number()
})


/**
 * @summary Create a product
 */
export const CreateProductBody = zod.object({
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().optional(),
  "price": zod.number(),
  "comparePrice": zod.number().optional(),
  "imageUrl": zod.string().optional(),
  "images": zod.array(zod.string()).optional(),
  "stock": zod.number(),
  "sku": zod.string().optional(),
  "categoryId": zod.number(),
  "isFeatured": zod.boolean().optional()
})


/**
 * @summary List featured products for homepage
 */
export const ListFeaturedProductsResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().nullish(),
  "price": zod.number(),
  "comparePrice": zod.number().nullish(),
  "imageUrl": zod.string().nullish(),
  "images": zod.array(zod.string()).optional(),
  "stock": zod.number(),
  "sku": zod.string().nullish(),
  "categoryId": zod.number(),
  "categoryName": zod.string().nullish(),
  "isFeatured": zod.boolean().optional(),
  "rating": zod.number().nullish(),
  "reviewCount": zod.number().optional(),
  "createdAt": zod.string().optional()
})
export const ListFeaturedProductsResponse = zod.array(ListFeaturedProductsResponseItem)


/**
 * @summary Get a product by ID
 */
export const GetProductParams = zod.object({
  "id": zod.coerce.number()
})

export const GetProductResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().nullish(),
  "price": zod.number(),
  "comparePrice": zod.number().nullish(),
  "imageUrl": zod.string().nullish(),
  "images": zod.array(zod.string()).optional(),
  "stock": zod.number(),
  "sku": zod.string().nullish(),
  "categoryId": zod.number(),
  "categoryName": zod.string().nullish(),
  "isFeatured": zod.boolean().optional(),
  "rating": zod.number().nullish(),
  "reviewCount": zod.number().optional(),
  "createdAt": zod.string().optional()
})


/**
 * @summary Update a product
 */
export const UpdateProductParams = zod.object({
  "id": zod.coerce.number()
})

export const UpdateProductBody = zod.object({
  "name": zod.string().optional(),
  "slug": zod.string().optional(),
  "description": zod.string().optional(),
  "price": zod.number().optional(),
  "comparePrice": zod.number().optional(),
  "imageUrl": zod.string().optional(),
  "images": zod.array(zod.string()).optional(),
  "stock": zod.number().optional(),
  "sku": zod.string().optional(),
  "categoryId": zod.number().optional(),
  "isFeatured": zod.boolean().optional()
})

export const UpdateProductResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().nullish(),
  "price": zod.number(),
  "comparePrice": zod.number().nullish(),
  "imageUrl": zod.string().nullish(),
  "images": zod.array(zod.string()).optional(),
  "stock": zod.number(),
  "sku": zod.string().nullish(),
  "categoryId": zod.number(),
  "categoryName": zod.string().nullish(),
  "isFeatured": zod.boolean().optional(),
  "rating": zod.number().nullish(),
  "reviewCount": zod.number().optional(),
  "createdAt": zod.string().optional()
})


/**
 * @summary Delete a product
 */
export const DeleteProductParams = zod.object({
  "id": zod.coerce.number()
})


/**
 * @summary Get cart items (by session)
 */
export const GetCartQueryParams = zod.object({
  "sessionId": zod.coerce.string()
})

export const GetCartResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.number(),
  "sessionId": zod.string(),
  "productId": zod.number(),
  "productName": zod.string().optional(),
  "productImageUrl": zod.string().nullish(),
  "quantity": zod.number(),
  "price": zod.number()
})),
  "subtotal": zod.number(),
  "itemCount": zod.number()
})


/**
 * @summary Add item to cart
 */
export const AddToCartBody = zod.object({
  "sessionId": zod.string(),
  "productId": zod.number(),
  "quantity": zod.number()
})


/**
 * @summary Update cart item quantity
 */
export const UpdateCartItemParams = zod.object({
  "id": zod.coerce.number()
})

export const UpdateCartItemBody = zod.object({
  "quantity": zod.number()
})

export const UpdateCartItemResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.number(),
  "sessionId": zod.string(),
  "productId": zod.number(),
  "productName": zod.string().optional(),
  "productImageUrl": zod.string().nullish(),
  "quantity": zod.number(),
  "price": zod.number()
})),
  "subtotal": zod.number(),
  "itemCount": zod.number()
})


/**
 * @summary Remove item from cart
 */
export const RemoveCartItemParams = zod.object({
  "id": zod.coerce.number()
})

export const RemoveCartItemResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.number(),
  "sessionId": zod.string(),
  "productId": zod.number(),
  "productName": zod.string().optional(),
  "productImageUrl": zod.string().nullish(),
  "quantity": zod.number(),
  "price": zod.number()
})),
  "subtotal": zod.number(),
  "itemCount": zod.number()
})


/**
 * @summary Clear all items from cart
 */
export const ClearCartQueryParams = zod.object({
  "sessionId": zod.coerce.string()
})


/**
 * @summary List orders with optional filters
 */
export const ListOrdersQueryParams = zod.object({
  "status": zod.coerce.string().optional(),
  "customerId": zod.coerce.number().optional(),
  "page": zod.coerce.number().optional(),
  "limit": zod.coerce.number().optional()
})

export const ListOrdersResponse = zod.object({
  "orders": zod.array(zod.object({
  "id": zod.number(),
  "customerId": zod.number().nullish(),
  "customerName": zod.string().optional(),
  "customerEmail": zod.string().optional(),
  "customerPhone": zod.string().nullish(),
  "shippingAddress": zod.string().optional(),
  "shippingCity": zod.string().optional(),
  "shippingCountry": zod.string().optional(),
  "status": zod.enum(['pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled']),
  "subtotal": zod.number().optional(),
  "shippingCost": zod.number().optional(),
  "total": zod.number(),
  "notes": zod.string().nullish(),
  "items": zod.array(zod.object({
  "id": zod.number(),
  "orderId": zod.number(),
  "productId": zod.number(),
  "productName": zod.string().optional(),
  "productImageUrl": zod.string().nullish(),
  "quantity": zod.number(),
  "unitPrice": zod.number(),
  "total": zod.number()
})).optional(),
  "createdAt": zod.string(),
  "updatedAt": zod.string().optional()
})),
  "total": zod.number(),
  "page": zod.number(),
  "limit": zod.number()
})


/**
 * @summary Place a new order
 */
export const CreateOrderBody = zod.object({
  "customerId": zod.number().optional(),
  "customerName": zod.string(),
  "customerEmail": zod.string(),
  "customerPhone": zod.string().optional(),
  "shippingAddress": zod.string(),
  "shippingCity": zod.string(),
  "shippingCountry": zod.string(),
  "notes": zod.string().optional(),
  "sessionId": zod.string().optional(),
  "items": zod.array(zod.object({
  "productId": zod.number(),
  "quantity": zod.number()
}))
})


/**
 * @summary Get an order by ID
 */
export const GetOrderParams = zod.object({
  "id": zod.coerce.number()
})

export const GetOrderResponse = zod.object({
  "id": zod.number(),
  "customerId": zod.number().nullish(),
  "customerName": zod.string().optional(),
  "customerEmail": zod.string().optional(),
  "customerPhone": zod.string().nullish(),
  "shippingAddress": zod.string().optional(),
  "shippingCity": zod.string().optional(),
  "shippingCountry": zod.string().optional(),
  "status": zod.enum(['pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled']),
  "subtotal": zod.number().optional(),
  "shippingCost": zod.number().optional(),
  "total": zod.number(),
  "notes": zod.string().nullish(),
  "items": zod.array(zod.object({
  "id": zod.number(),
  "orderId": zod.number(),
  "productId": zod.number(),
  "productName": zod.string().optional(),
  "productImageUrl": zod.string().nullish(),
  "quantity": zod.number(),
  "unitPrice": zod.number(),
  "total": zod.number()
})).optional(),
  "createdAt": zod.string(),
  "updatedAt": zod.string().optional()
})


/**
 * @summary Update order status
 */
export const UpdateOrderStatusParams = zod.object({
  "id": zod.coerce.number()
})

export const UpdateOrderStatusBody = zod.object({
  "status": zod.enum(['pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled'])
})

export const UpdateOrderStatusResponse = zod.object({
  "id": zod.number(),
  "customerId": zod.number().nullish(),
  "customerName": zod.string().optional(),
  "customerEmail": zod.string().optional(),
  "customerPhone": zod.string().nullish(),
  "shippingAddress": zod.string().optional(),
  "shippingCity": zod.string().optional(),
  "shippingCountry": zod.string().optional(),
  "status": zod.enum(['pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled']),
  "subtotal": zod.number().optional(),
  "shippingCost": zod.number().optional(),
  "total": zod.number(),
  "notes": zod.string().nullish(),
  "items": zod.array(zod.object({
  "id": zod.number(),
  "orderId": zod.number(),
  "productId": zod.number(),
  "productName": zod.string().optional(),
  "productImageUrl": zod.string().nullish(),
  "quantity": zod.number(),
  "unitPrice": zod.number(),
  "total": zod.number()
})).optional(),
  "createdAt": zod.string(),
  "updatedAt": zod.string().optional()
})


/**
 * @summary List customers
 */
export const ListCustomersQueryParams = zod.object({
  "search": zod.coerce.string().optional(),
  "page": zod.coerce.number().optional(),
  "limit": zod.coerce.number().optional()
})

export const ListCustomersResponse = zod.object({
  "customers": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "email": zod.string(),
  "phone": zod.string().nullish(),
  "address": zod.string().nullish(),
  "city": zod.string().nullish(),
  "country": zod.string().nullish(),
  "orderCount": zod.number().optional(),
  "totalSpent": zod.number().optional(),
  "createdAt": zod.string()
})),
  "total": zod.number(),
  "page": zod.number(),
  "limit": zod.number()
})


/**
 * @summary Create a customer
 */
export const CreateCustomerBody = zod.object({
  "name": zod.string(),
  "email": zod.string(),
  "phone": zod.string().optional(),
  "address": zod.string().optional(),
  "city": zod.string().optional(),
  "country": zod.string().optional()
})


/**
 * @summary Get a customer by ID
 */
export const GetCustomerParams = zod.object({
  "id": zod.coerce.number()
})

export const GetCustomerResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "email": zod.string(),
  "phone": zod.string().nullish(),
  "address": zod.string().nullish(),
  "city": zod.string().nullish(),
  "country": zod.string().nullish(),
  "orderCount": zod.number().optional(),
  "totalSpent": zod.number().optional(),
  "createdAt": zod.string()
})


/**
 * @summary Get overall dashboard stats
 */
export const GetDashboardStatsResponse = zod.object({
  "totalOrders": zod.number(),
  "totalRevenue": zod.number(),
  "totalProducts": zod.number(),
  "totalCustomers": zod.number(),
  "pendingOrders": zod.number(),
  "todayOrders": zod.number(),
  "todayRevenue": zod.number()
})


/**
 * @summary Get recent orders for dashboard
 */
export const GetRecentOrdersQueryParams = zod.object({
  "limit": zod.coerce.number().optional()
})

export const GetRecentOrdersResponseItem = zod.object({
  "id": zod.number(),
  "customerId": zod.number().nullish(),
  "customerName": zod.string().optional(),
  "customerEmail": zod.string().optional(),
  "customerPhone": zod.string().nullish(),
  "shippingAddress": zod.string().optional(),
  "shippingCity": zod.string().optional(),
  "shippingCountry": zod.string().optional(),
  "status": zod.enum(['pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled']),
  "subtotal": zod.number().optional(),
  "shippingCost": zod.number().optional(),
  "total": zod.number(),
  "notes": zod.string().nullish(),
  "items": zod.array(zod.object({
  "id": zod.number(),
  "orderId": zod.number(),
  "productId": zod.number(),
  "productName": zod.string().optional(),
  "productImageUrl": zod.string().nullish(),
  "quantity": zod.number(),
  "unitPrice": zod.number(),
  "total": zod.number()
})).optional(),
  "createdAt": zod.string(),
  "updatedAt": zod.string().optional()
})
export const GetRecentOrdersResponse = zod.array(GetRecentOrdersResponseItem)


/**
 * @summary Get sales breakdown by category
 */
export const GetSalesByCategoryResponseItem = zod.object({
  "categoryId": zod.number(),
  "categoryName": zod.string(),
  "totalSales": zod.number(),
  "orderCount": zod.number()
})
export const GetSalesByCategoryResponse = zod.array(GetSalesByCategoryResponseItem)


/**
 * @summary Get top selling products
 */
export const GetTopProductsQueryParams = zod.object({
  "limit": zod.coerce.number().optional()
})

export const GetTopProductsResponseItem = zod.object({
  "productId": zod.number(),
  "productName": zod.string(),
  "productImageUrl": zod.string().nullish(),
  "totalSold": zod.number(),
  "revenue": zod.number()
})
export const GetTopProductsResponse = zod.array(GetTopProductsResponseItem)


