/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * E-commerce store API
 * OpenAPI spec version: 0.1.0
 */
import type { OrderItem } from './orderItem';
import type { OrderStatus } from './orderStatus';

export interface Order {
  id: number;
  /** @nullable */
  customerId?: number | null;
  customerName?: string;
  customerEmail?: string;
  /** @nullable */
  customerPhone?: string | null;
  shippingAddress?: string;
  shippingCity?: string;
  shippingCountry?: string;
  status: OrderStatus;
  subtotal?: number;
  shippingCost?: number;
  total: number;
  /** @nullable */
  notes?: string | null;
  items?: OrderItem[];
  createdAt: string;
  updatedAt?: string;
}
